# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
    
    desc "distributing APK using Firebase App Distributions"
    lane :distribute_apk do
        build_android_app(
        task: "assemble",
        flavor: "Production",
        build_type: "Release",
        )
        
        release = firebase_app_distribution(
            app: ENV['FIREBASE_APP_ID'],
            firebase_cli_token: ENV['FIREBASE_TOKEN'],
            testers: "ahmad.abdelhamid35@gmail.com",
            release_notes: "Lots of amazing new features to test out!",
            android_artifact_type: "APK",
        )
        gradle(task: "clean")
    end
    
    
    desc "distributing AAB using Firebase App Distributions"
    lane :distribute_aap do
#        gradle(task: "clean assembleRelease")
        build_android_app(
        task: "bundle",
        flavor: "Production",
        build_type: "Release",
        )

        release = firebase_app_distribution(
            app: ENV['FIREBASE_APP_ID'],
            firebase_cli_token: ENV['FIREBASE_TOKEN'],
            testers: "ahmad.abdelhamid35@gmail.com",
            release_notes: "Lots of amazing new features to test out!",
            android_artifact_type: "AAB",
        )

    end
end
