name: deploy & build

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo in runner
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle Cache
        uses: burrunan/gradle-cache-action@v1

      - name: Grant execution permission to gradlew
        run: chmod +x gradlew

      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: decode_keystore
        with:
          fileName: "upload-keystore.keystore"
          encodedString: ${{ secrets.STORE_FILE_B64 }}

      - name: Build & deploy Android release
        run: ./gradlew assembleRelease appDistributionUploadProductionRelease
        env:
#          KEYSTORE_FILE: ${{ steps.upload-keystore.keystore.outputs.filePath }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS}}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

#      - name: Build & deploy production-release
#        run: ./gradlew assembleRelease appDistributionUploadProductionRelease
#        env:
#          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}