name: deploy & build

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo in runner
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle Cache
        uses: burrunan/gradle-cache-action@v1

      - name: Grant execution permission to gradlew
        run: chmod +x gradlew

      - name: Build & deploy production-release
        run: ./gradlew assembleRelease appDistributionUploadProductionRelease
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}