name: deploy & build

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo in runner
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle Cache
        uses: burrunan/gradle-cache-action@v1

      - name: Grant execution permission to gradlew
        run: chmod +x gradlew

      - name: Configure Keystore
        run: |
          echo "$STORE_FILE_B64" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > app/keystore.jks
          echo "storeFile=keystore.jks" >> keystore.properties
          echo "keyAlias=$KEY_ALIAS" >> keystore.properties
          echo "storePassword=$STORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
        env:
          STORE_FILE_B64: ${{ secrets.STORE_FILE_B64 }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS}}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

      - name: Build & deploy Android release
        run: ./gradlew assembleRelease appDistributionUploadProductionRelease --artifactType="AAB"
        env:
          STORE_FILE_B64: ${{ secrets.STORE_FILE_B64 }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS}}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

#      - name: Build & deploy production-release
#        run: ./gradlew assembleRelease appDistributionUploadProductionRelease
#        env:
#          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}