name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout current repository in runner
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          cache: 'gradle'

      - name: Cache Gradle
        uses: actions/cache@v3
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - run: bundle exec rake

      - name: install fastlane
        run: |
          gem install bundler
          bundle install
          bundle exec fastlane install_plugins

      - name: Build and run tests
        run: bundle exec fastlane run_unit_tests

      - name: Check Test Results
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "All tests passed. The pull request can be merged."
          else
            echo "Tests failed. The workflow will be marked as failed, and the pull request cannot be merged."
            exit 1
          fi

      - name: Increase Version Number
        run: fastlane run_increase_version_number