name: Pull Request

on:
  pull_request:
    branches:
      - master
permissions: read-all|write-all

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout current repository in runner
        uses: actions/checkout@v3

      - name: Trigger Lint Workflow
        run: |
          gh workflow run lint.yml

  tests:
    needs: lint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout current repository in runner
        uses: actions/checkout@v3

      - name: Trigger Tests Workflow
        run: |
          gh workflow run tests.yml
