name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Lint Workflow
        uses: actions/workflow-dispatch@v2
        with:
          workflow: lint.yml

  tests:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Tests Workflow
        uses: actions/workflow-dispatch@v2
        with:
          workflow: tests.yml
